wandb_version: 1

model:
  desc: null
  value: AutoEncoder
dataset:
  desc: null
  value: residues
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701405901.28051
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.12.0
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
