wandb_version: 1

model:
  desc: null
  value: LSTMED
hyperparameters:
  desc: null
  value:
    batch_size: 512
    dropout:
    - 0
    - 0
    hidden_size: 6
    lr: 0.01
    n_layers:
    - 1
    - 1
    num_epochs: 30
    sequence_len: 25
    alm_threshold: 2.2
dataset:
  desc: null
  value: residues_27421
job_type:
  desc: null
  value: best_model_training
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703303803.209747
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 5
      - 14
      - 16
      - 23
      4: 3.12.0
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
