wandb_version: 1

model:
  desc: null
  value: VAE
hyperparameters:
  desc: null
  value:
    encoder_hidden_sizes:
    - 15
    - 10
    - 5
    decoder_hidden_sizes:
    - 5
    - 10
    - 15
    latent_size: 11
    sequence_len: 1
    kld_weight: 1.0
    dropout_rate: 0.0
    num_eval_samples: 5
    lr: 0.0005
    batch_size: 1024
    num_epochs: 500
    alm_threshold: 1.1
dataset:
  desc: null
  value: 'TS start_date: 946965292.0'
job_type:
  desc: null
  value: best_model_training
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701673027.106408
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      4: 3.12.0
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
